= GitHub

image::github.svg[align=center, width=25%]

== Purpose

https://github.com[GitHub] is a service that provides a space for remote git
repositories. It features an extensive web interface and several project
management features.

GitHub has become a popular service for open source projects and is a
https://pydanny.blogspot.com/2011/08/github-is-my-resume.html[great way]
to showcase your projects to prospective employers. It is free to sign up for
GitHub and we will be using it for project management. It is recommended that
you sign up with your .edu email address. This way you will have an _academic_
account to showcase your work.

== Remote Repositories

To set up a remote repository in GitHub, follow these steps:

. Create a local git repository as shown in the <<git, previous section>>.
  Choose a repository name that is simple. Avoid spaces or trailing dashes as
  various tools may have trouble with them.
. Sign in to GitHub and navigate to https://github.com/new[Create a New
  Repository]
. Put in the repository name (make sure it matches the local repository
  name) and a description.
. GitHub now offers unlimited private repositories with unlimited
  collaborators. This means you could complete your project in a private
  repository. If you choose to use a private repository, be sure to add your
  instructor as a collaborator. Later when you want to showcase your work you
  can make this repository public. You could also start with a public repository
  which can provide good practice for learning to keep secrets (passwords,
  API keys, etc.) out of your commits. In this case you will still need to add
  group members as collaborators, but your instructor should have read-only
  access without any additional setup.
. Once you click "Create Repository", instructions will be provided for setting
  the remote on your local repository. It is very similar to the scenario
  covered in the <<git, previous section>>. Follow the directions.
. Now your group members should be able to `clone` the repository, but they will
  not be able to make commits until you invite them as collaborators.
. Go to _Settings (top right gear icon) -> Manage access -> Invite a
  Collaborator_ within the GitHub web interface for your repository. Add all of
  your group members as collaborators.

== Issues

GitHub has a built-in bug tracker called _Issues_. It can be found next to the
_Code_ tab, under the repository name when viewing a repository. An issue is
typically a bug that needs to be fixed or a feature that needs to be
implemented. It can be assigned to a project collaborator and it can be closed
when it is resolved. Issues can also be linked to a milestone, which can be
thought of as as group of things that need to be done to reach a particular
phase.

We will be using the GitHub Issues to monitor individual contributions to a
project and to assess how well a team functions. Do not be afraid to create
issues and use the discussion features inside of them. They help groups document
their progress. Groups will also have milestones assigned as they progress
through the text. Groups should create those milestones in GitHub and assign
the goals to collaborators as issues.

== Pull requests

For complex projects or projects that have external contributers GitHub
supports a fork-based pull request (PR) workflow. Although we probably won't
be using it too much, it is helpful to know how it works in case you end up
working on larger projects, you want to contribute to another project, or your
instructor wants to contribute to your project.

In GitHub, a typical PR workflow looks like this:

.Pull Request
[plantuml, pr, svg]
....
@startuml

|Project|
:repo;
|Contributer|
-> fork;
:copy of repo;
-> make changes;
:staged repo;
-> commit;
:updated repo;
-> create diff;
:pull request;
|Project|
-> submit PR;
if (Accept PR?) then (yes)
  :apply changes to repo;
  :commit;
else (no)
  :do not apply changes;
endif

@enduml
....

A contributer forks a project (makes their own personal copy), which is as easy
as clicking the _Fork_ button in the upper-right when viewing a project
repository. They change the parts of the repository that they want to in their
personal copy and commit their changes. Then they click on _Pull Requests ->
Create Pull Request_ on the project's repository. GitHub defaults to creating
PRs across branches (a good technique when working on a large project with lots
of contributers), but you can select PRs across forks as well. The owner of the
project can review the PR and if they like the changes they have the option to
merge them with their repository.

== Documentation

GitHub supports several styles of documentation, but the most common is
https://en.wikipedia.org/wiki/Markdown[Markdown]. Files written in Markdown and
ending in the `.md` extension will be rendered and displayed when viewed in the
GitHub web interface. If a file named `README.md` exists in a directory, it
will be automatically displayed at the bottom of a directory listing. This
makes it easy to build documentation right into your repository. Learn Markdown
and be sure to have a `README.md` in your repository.footnote:[If you're looking
to take things a bit further https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc],
https://docutils.sourceforge.io/rst.html[reStructuredText], and
https://docs.racket-lang.org/scribble/[scribble] are worth exploring too. This
book was written using AsciiDoc.]

== Resources

* https://guides.github.com/features/issues[Mastering Issues]
* https://www.atlassian.com/git/tutorials/making-a-pull-request[Making a Pull Request]
* https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests[
  About Pull Requests]
* https://www.markdownguide.org[The Markdown Guide]
* https://www.markdowntutorial.com[Markdown Tutorial]

== Questions

[qanda]
What does GitHub provide for a project?::
    GitHub provides a remote repository and several project management tools
    including an issue tracker. Both the repository and the tools have built-in
    web interfaces.
What is the difference between using git and GitHub?::
    git is the version control system and GitHub is a website that provides
    additional project management tools and a web interface for a git
    repository. git can be used independently of GitHub.
A new member joins your team. As the maintainer of the repository on GitHub, what steps do you need to take so that they have commit access to the repository? What steps does the group member need to take to get set up?::
    The team member will need to set up a GitHub account and tell you what
    their user name is. Once they have done that, you will need to add them
    as a collaborator to the repository that you want to share with them.
What is the purpose of issues in GitHub?::
    Issues allow you to keep track of bugs that need to be fixed, milestones
    that need to be completed, or other general TODO items. It also gives you
    a place to have a dialog about the project you are working on.
Why might a team want to use pull requests instead of adding all contributers as collaborators to a project?::
    Even though all changes in a git repository can be rolled back if needed,
    it can be time consuming and annoying for a large project to have to keep
    reverting changes. By having contributers submit PRs, an integration team
    can review the changes and only commit code that meets their standards.
