= Kubernetes
:sourcedir: minikube-demo

image::k8s-logo.svg[alt="Kubernetes Logo",width=25%,align=center]

== Introduction

Kubernetes is a container orchestration system originally designed by Google.
It is currently the most popular orchestration system and is notorious for
being difficult to learn. Fortunately, we have already covered most of the
concepts and the command syntax is similar to Docker.

A Kubernetes cluster is made up of nodes. Each node is capable of running
pods, which in turn are running containers:

.Kubernetes Cluster
[plantuml, k8s_cluster, svg]
....
@startuml

node node1
node node2

rectangle pod1
rectangle pod2
rectangle pod3
rectangle pod4
rectangle pod5

rectangle container1
rectangle container2
rectangle container3
rectangle container4
rectangle container5
rectangle container6

node1 -- pod1
node1 -- pod2
node1 -- pod3

node2 -- pod4
node2 -- pod5

pod1 -- container1
pod1 -- container2
pod2 -- container3
pod3 -- container4
pod4 -- container5
pod5 -- container6

node1 - node2

@enduml
....

Kubernetes is designed to solve the hard problems of multi-node deployment,
replication, volume sharing, container communication, updates, roll-backs,
service discovery and monitoring. It does this by defining objects and
providing an API to interact with them. Some of the first objects we will be
working with are: 

Deployment:: Defines how to handle the creation / maintenance of pods
Service:: Defines what pods offer to the cluster and how it should be accessed

== Minikube

For our purposes we will be using a single-node, local version of Kubernetes
called https://kubernetes.io/docs/tasks/tools/install-minikube/[minikube].
minikube acts as a single-node cluster by running Linux in a virtual machine on
the host. It provides a several options for how the VM is run:

.Minikube Architecture
[plantuml, minikube_arch, svg]
....
@startuml

rectangle "Operating System" {
    rectangle Windows
    rectangle MacOS
    rectangle Linux
}

rectangle "Driver" {
    rectangle hyperv [
        Hyper-V
    ]
    rectangle VirtualBox
    rectangle docker_h [
        Docker (on host, experimental)
    ]
    rectangle none [
        None (native)
    ]
}

rectangle "Minikube Node" {
    rectangle linux [
        Linux VM
    ]
    rectangle docker_vm [
        Docker (on VM)
    ]
    rectangle Kubernetes
}

docker_vm -> Kubernetes
Kubernetes -> docker_vm
Kubernetes --> linux
docker_vm --> linux
linux --> hyperv
linux --> VirtualBox
linux --> docker_h
linux --> none
hyperv --> Windows
VirtualBox --> Windows
docker_h --> Windows
VirtualBox --> MacOS
docker_h --> MacOS
VirtualBox --> Linux
docker_h --> Linux
none --> Linux

@enduml
....

https://kubernetes.io/docs/tasks/tools/install-minikube/[Follow these directions
to install minikube.] There are a few virtualization options depending on the
OS that you are running.

WARNING: If you have Docker Desktop running, minikube defaults to the Docker
driver. This driver is still experimental and may not work well. You can
explicitly specify another driver when you start minikube with the `--driver=`
option.

WARNING: Hyper-V and VirtualBox were still mutually exclusive in Windows at the
time of this writing. You will need to choose one or the other.

WARNING: Hyper-V will require you to run your commands as an Administrator.

When you start minikube, you should see output similar to the following:

[source, shell]
----
PS minikube-demo> minikube start --driver=hyperv
* minikube v1.9.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Using the hyperv driver based on existing profile
* Retarting existing hyperv VM for "minikube" ...
* Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
* Enabling addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
----

TIP: If you get errors due to low memory, close a few applications and try
again. Typically you can restart the applications after minikube is running.

Kubernetes will attempt to pull all container images from a container
repository by default. To avoid having to upload our images to a repository, we
can set environment variables in our terminal so that we interact with the
Docker daemon _inside_ our minikube virtual
machine.footnote:[
https://medium.com/@maumribeiro/running-your-own-docker-images-in-minikube-for-windows-ea7383d931f6[
See this great blog post for more details]] Fortunately, minikube has the
`docker-env` command to make this easier:

[source, shell]
----
PS minikube-demo> minikube docker-env | Invoke-Expression
PS minikube-demo> docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED    
1bf91c2ca7df        4689081edb10           "/storage-provisioner"   7 minutes ago
a9866f5f5838        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
03a4f7f5e320        67da37a9a360           "/coredns -conf /etc…"   7 minutes ago
05061b993702        67da37a9a360           "/coredns -conf /etc…"   7 minutes ago
78977b068886        43940c34f24f           "/usr/local/bin/kube…"   7 minutes ago
b5312ba91086        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
968acc692934        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
0a72059bbe5f        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
d9c5aa3d43d0        303ce5db0e90           "etcd --advertise-cl…"   7 minutes ago
21b09398206f        74060cea7f70           "kube-apiserver --ad…"   7 minutes ago
313982f14a1c        d3e55153f52f           "kube-controller-man…"   7 minutes ago
35813d25f0bf        a31f78c7c8ce           "kube-scheduler --au…"   7 minutes ago
e6cdb564a306        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
b6bfe0e6f093        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
da47e560edab        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
3c599f97ecec        k8s.gcr.io/pause:3.2   "/pause"                 7 minutes ago
----

As can be seen from the output of the `docker ps` command, our Kubernetes
cluster is made up of many containers running in a VM. If you ran `docker ps`
without setting up the environment first, you would only see the containers you
had running on your local Docker daemon (which may actually be
https://inception.davepedu.com/[running on a VM itself] if you are using Docker
Toolbox).

TIP: `minikube` commands will work in a new terminal, but if you want to build
docker images and have them available on your Kubernetes cluster you will need
to use minikube's docker-env command for each new terminal you open.

TIP: If you are experiencing errors with minikube, the first thing you should
try is running `minikube delete` and `minikube start --driver=<your driver>`.
This addresses the vast majority of issues by wiping all traces of the old VM,
creating a new one, and starting fresh.

minikube includes a popular command line tool called kubectl. This is the
command that we will be using for interacting with our Kubernetes cluster. To
show that everything is working, lets create and build a basic Dockerfile that
should print some output to standard out:

.{sourcedir}/Dockerfile
[source, Dockerfile]
----
include::{sourceroot}/{sourcedir}/Dockerfile[]
----

[source, shell]
----
PS minikube-demo> docker build -t k8s-example:v1 .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
aad63a933944: Pull complete
Digest: sha256:b276d875eeed9c7d3f1cfa7edb06b22ed22b14219a7d67c52c56612330348239
Status: Downloaded newer image for alpine:latest
 ---> a187dde48cd2
Step 2/2 : ENTRYPOINT ["/bin/sh", "-c", "echo 'Hello from a Kubernetes log!'; sleep 30"]
 ---> Running in 96c1739d805e
Removing intermediate container 96c1739d805e
 ---> 7b9898952ce0
Successfully built 7b9898952ce0
Successfully tagged k8s-example:v1
----

WARNING: We built our image with a tag _and_ a version. You need the tag so you
can reference it from Kubernetes. If you don't specify a version Kubernetes
will try to pull the `latest` from a repository.

Now we'll create a deployment, which by default will make one pod that runs
your image. We also run the `get deployment` and `get pod` commands so we can
see the outcome. Lastly, we will inspect the logs for the pod that was created.

[source, shell]
----
PS minikube-demo> kubectl create deployment k8s-example --image=k8s-example:v1
deployment.apps/k8s-example created
PS minikube-demo> kubectl get deployment
NAME          READY   UP-TO-DATE   AVAILABLE   AGE
k8s-example   1/1     1            1           7s
PS minikube-demo> kubectl get pod
NAME                           READY   STATUS    RESTARTS   AGE
k8s-example-5787cd97dc-ft2cr   1/1     Running   0          12s
PS minikube-demo> kubectl logs k8s-example-5787cd97dc-ft2cr
Hello from a Kubernetes log!
----

Our image is up and running, but remember that after 30 seconds it should exit.
As an orchestration system, Kubernetes defaults to restarting pods that have
stopped. Lets wait a while (14 minutes to be exact) and then execute the `get
pod` command again:

[source, shell]
----
PS minikube-demo> kubectl get pod
NAME                           READY   STATUS             RESTARTS   AGE
k8s-example-5787cd97dc-ft2cr   0/1     CrashLoopBackOff   6          14m
----

Kubernetes has restarted our pod six times now. In fact, it restarted it so
much that it is now waiting before trying again (`CrashLoopBackOff`). You now
have a minikube single-node Kubernetes cluster running on your local machine.
You can build custom Docker images and have them run on your cluster.

To bring everything down, use the `delete deployment` command:

[source, shell]
----
PS minikube-demo> kubectl delete deployment k8s-example
deployment.apps "k8s-example" deleted
PS minikube-demo> kubectl get pod
No resources found in default namespace.
----

== Debugging

The official Kubernetes documentation has an
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/[
excellent article] on debugging services. What follows are some tips they may
help reinforce or fill-in-the-blanks for topics in the article.

Two `kubectl` commands are especially useful for finding out more information
about an object:

`kubectl get`:: gets brief information about an object or all of the objects of
that type
`kubectl describe`:: gets more information about an object

Let's take a look:

[source, shell]
----
PS minikube-demo> kubectl get pod
NAME                           READY   STATUS    RESTARTS   AGE
k8s-example-5787cd97dc-fbrxl   1/1     Running   0          33s
PS minikube-demo> kubectl describe pod k8s-example-5787cd97dc-fbrxl
Name:         k8s-example-5787cd97dc-fbrxl
Namespace:    default
Priority:     0
Node:         minikube/172.17.0.2
Start Time:   Mon, 13 Apr 2020 18:22:39 -0400
Labels:       app=k8s-example
              pod-template-hash=5787cd97dc
Annotations:  <none>
Status:       Running
IP:           172.18.0.3
IPs:
  IP:           172.18.0.3
Controlled By:  ReplicaSet/k8s-example-5787cd97dc
Containers:
  k8s-example:
    Container ID:   docker://f22a1be8401f256c42c8c8ad82cf6757bc9e34ec7ae1fe0c4329fff57ff09bcb
    Image:          k8s-example:v1
    Image ID:       docker://sha256:374b52c1385d25269a05e9542e65690fe9dc00146b869580db8ab51b5027096a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 13 Apr 2020 18:23:37 -0400
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 13 Apr 2020 18:23:06 -0400
      Finished:     Mon, 13 Apr 2020 18:23:36 -0400
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5mgft (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-5mgft:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5mgft
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  <unknown>          default-scheduler  Successfully assigned default/k8s-example-5787cd97dc-fbrxl to minikube
  Normal   BackOff    62s                kubelet, minikube  Back-off pulling image "k8s-example:v1"
  Warning  Failed     62s                kubelet, minikube  Error: ImagePullBackOff
  Normal   Pulling    50s (x2 over 62s)  kubelet, minikube  Pulling image "k8s-example:v1"
  Warning  Failed     50s (x2 over 62s)  kubelet, minikube  Failed to pull image "k8s-example:v1": rpc error: code = Unknown desc = Error
 response from daemon: pull access denied for k8s-example, repository does not exist or may require 'docker login': denied: requested acc
ess to the resource is denied
  Warning  Failed     50s (x2 over 62s)  kubelet, minikube  Error: ErrImagePull
  Normal   Pulled     5s (x2 over 36s)   kubelet, minikube  Container image "k8s-example:v1" already present on machine
  Normal   Created    5s (x2 over 36s)   kubelet, minikube  Created container k8s-example
  Normal   Started    5s (x2 over 36s)   kubelet, minikube  Started container k8s-example
----

As you can see there, is lots of useful information here including a full
history of events that have occured.

Many of the same techniques used for debugging Docker images can be used for
debugging Kubernetes objects. For example you can execute interactive commands
(including a shell) on running docker images with `kubectl exec -it`:

[source, shell]
----
PS minikube-demo> kubectl exec -it k8s-example-5787cd97dc-7j6cc -- /bin/sh
/ # ps ax
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 30
   11 root      0:00 /bin/sh
   16 root      0:00 ps ax
/ # ls
bin    dev    etc    home   lib    media  mnt    opt    proc   root   run    sbin   srv    sys    tmp    usr    var
/ # exit
----

If, for some reason, an image does not start up, you can replace the ENTRYPOINT
of the Dockerfile from within the `template` definition of a *Deployment*. By
replacing it with something you know will work, you can then execute an
interactive shell in the container to see what is going on. The following is an
example of executing the sleep command, assuring that the pod will run for at
least an hour:

[source, YAML]
----
kind: Deployment
metadata:
  name: db-rw
  labels:
    app: db-rw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-rw
  template:
    metadata:
      labels:
        app: db-rw
    spec:
      containers:
        - name: db-rw
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "changeme"
            - name: POSTGRES_REPLICA_PASSWORD
              value: "changeme"
          command: ["bash", "-c", "sleep 3600"]
----

Sometimes your objects are applied, but no pods start up. This may mean
that Kubernetes started your *Deployment* or *StatefulSet* which created a
https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/[
*ReplicaSet*], but the *ReplicaSet* was unable to start your pods. Try running
`kubectl get replicaset` to find which *ReplicaSet* is running and then
`kubectl describe replicaset <replicaset_name>` where <replicaset_name> is the
name of your *ReplicaSet*.

Finally, you may find yourself in a situation where you need to run `kubectl`
from within a pod. This can be helpful for sorting out role based access
control issues, namely "how can this pod interact with the Kubernetes API?"
https://itnext.io/running-kubectl-commands-from-within-a-pod-b303e8176088[
This guide] is a great resource. It largely boils down to:

. From within the pod (`kubectl exec -it <pod-name> -- bash`) install curl:
  `apt-get install curl`.
. Download `kubectl`:
.. `VERSION=curl https://storage.googleapis.com/kubernetes-release/release/stable.txt`
.. `curl -LO https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl`
. Make it executable and install it:
.. `chmod +x ./kubectl`
.. `mv ./kubectl /usr/local/bin/`

== Conclusion

Hopefully you can see the benefit of working with an orchestration framework.
While it may be daunting at first to learn all of the objects and to use new,
unfamiliar commands, Kubernetes does provide a lot of options for someone
looking to deploy scalable applications. Kubernetes has emerged as the
https://www.forbes.com/sites/udinachmany/2018/11/01/kubernetes-evolution-of-an-it-revolution/#67e70c2454e1[
de facto standard] and knowing how to use it is a _very_ marketable skill.

== Questions

[qanda]
What is the role of a pod in Kubernetes?::
    {empty}
What does a *Deployment* do?::
    {empty}
What is minikube used for and what platforms can it run on?::
    {empty}
If you were given an image to deploy on Kubernetes and it continually failed to start, what steps would you take to figure out what was going wrong?::
    {empty}
